version: 3.1.{build}
configuration: Release
services: postgresql12

before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  
artifacts:
- path: src/**/*.nupkg
  name: NuGet Packages
